### PR TITLE
Adds GitHub setup files

### LINKED ISSUE #110: Update GitHub setup files
Check all below:

```[tasklist]
### Tasks
- [x] Issue and discussion templates ([like Foundry does](https://github.com/foundry-rs/foundry/issues/new/choose))
- [x] CODEOWNERS
- [x] PR template
- [x] (optionally) CONTRIBUTING.md
- [x] SECURITY.md
- [x] LICENSE
```

### PR DESCRIPTION
**Pull request by arthurgousset**
### Description

- Changes LICENSE from MIT to Apache 2.0. This is consistent with the other packages in [`celo-org/developer-tooling`](https://github.com/celo-org/developer-tooling)
- Adds bug report and feature request template
- Adds `CONTRIBUTING.md` file

### Other changes

None

### Tested

Only docs changes.

### Related issues

- Fixes #110 

### Backwards compatibility

Yes

### Documentation

Yes

### CODE REVIEW

**Comment by arthurgousset** [comment]
Blocked by 
- https://github.com/celo-org/rainbowkit-celo/issues/86

Once all wallets are in the upstream repo and a simple migration guide exists, I'll update the README in this PR and merge it.

**Comment by arthurgousset** [comment]
Maybe I should take the README commit out of this PR, so it can be merged and open a draft README PR for when we are ready to move forward with deprecating the package.

**Comment by arthurgousset** [comment]
Removed the incomplete disclaimer that this package might be deprecated in the `README.md` file.

**Comment by arthurgousset** [comment]
> Maybe I should take the README commit out of this PR, so it can be merged and open a draft README PR for when we are ready to move forward with deprecating the package.

That's done ✅ I removed the incomplete disclaimer that this package might be deprecated in the README.md file.
That should allow these changes to be merged without being blocked by any deprecation process.

**Review by aaronmgdr — APPROVED** [review]

**Pull request merged**
